# Generated by Django 5.2.3 on 2025-06-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harid', '0001_initial'),
        ('tolov', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='harid',
            name='harid_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harid',
            name='xizmat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolov.paymentshistory'),
        ),
    ]
