# Generated by Django 5.2.3 on 2025-06-16 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('poster', models.TextField()),
                ('body', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
                ('reting', models.IntegerField(default=0)),
                ('kurs_vaqti', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KursEgasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KursMavzu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('mavzu_name', models.CharField(max_length=255)),
                ('mavzu_matni', models.TextField()),
                ('media_resurslar', models.JSONField()),
                ('resurslar', models.JSONField()),
                ('media_time', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KursBolim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tartib_raqami', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.kurs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BolimTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('savol', models.CharField(max_length=355)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('test_javob', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=30)),
                ('bolim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.kursbolim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
